module.exports=
    name:"Deadly Trick"
    opening:""
    skin_tip:"你的身份"
    author:"一只小逗比"
    lastModified:"2026-08-15T07:29:36.745Z"
    vote:""
    sunrise:""
    sunset:""
    icon:""
    background_color:"#000000"
    color:"#ff00a6"
    lockable:true
    isAvailable:->
        return true
    skins:
        character_1:
            avatar:"https://pic1.imgdb.cn/i/0347S1oll3AB7ZKwsQzTrm.png"
            name:"华帆"
            prize:""
        character_2:
            avatar:"https://pic1.imgdb.cn/i/0347S1oejrD35rLIEk7gWc.png"
            name:"杰里米"
            prize:""
        character_3:
            avatar:"https://pic1.imgdb.cn/i/0347S1oMPad2YcaUec86sQ.png"
            name:"连"
            prize:""
        character_4:
            avatar:"https://pic1.imgdb.cn/i/0347S3YPdXhLR6FlFRKL63.png"
            name:"莉莉安娜"
            prize:""
        character_5:
            avatar:"https://pic1.imgdb.cn/i/0347S1ohf0IMIyk49J78Mg.png"
            name:"凛"
            prize:""
        character_6:
            avatar:"https://pic1.imgdb.cn/i/0347S3YOGrkNl2QaZOlHV2.png"
            name:"露娜"
            prize:""
        character_7:
            avatar:"https://pic1.imgdb.cn/i/0347S1pDLHfxNGjFmBlcB6.png"
            name:"路易斯"
            prize:""
        character_8:
            avatar:"https://pic1.imgdb.cn/i/0347S1pKGcJd6MZg9wCcvz.png"
            name:"美幸"
            prize:""
        character_9:
            avatar:"https://pic1.imgdb.cn/i/0347S1oKGZlSG5M6Qagm3v.png"
            name:"诺埃尔"
            prize:""
        character_10:
            avatar:"https://pic1.imgdb.cn/i/0347S1pOeXrHp3N1GRvkoY.png"
            name:"素伊"
            prize:""
        character_11:
            avatar:"https://pic1.imgdb.cn/i/0347S1pL8is08LqLzTAM6e.png"
            name:"夏诚"
            prize:""
        character_12:
            avatar:"https://pic1.imgdb.cn/i/0347S1pSeBDRrp1LLRm0v5.png"
            name:"雪"
            prize:""
