module.exports=
    name:"偶像大师"
    opening:"偶像大师闪耀色彩＋学园偶像大师"
    skin_tip:"你的身份"
    author:"05q、人生"
    lastModified:"2026-08-11T12:33:39.787Z"
    vote:""
    sunrise:""
    sunset:""
    icon:""
    background_color:"#000000"
    color:"#000000"
    lockable:true
    isAvailable:->
        return true
    skins:
        character_1:
            avatar:"https://s3.bmp.ovh/2026/08/12/cJBb8ABu.png"
            name:"花海咲季"
            prize:"Re;IRIS"
        character_2:
            avatar:"https://s3.bmp.ovh/2026/08/12/dl8ZOnzq.png"
            name:"月村手毬﻿"
            prize:"Re;IRIS"
        character_3:
            avatar:"https://s3.bmp.ovh/2026/08/12/l6z3kQPU.png"
            name:"藤田琴音"
            prize:"Re;IRIS"
        character_4:
            avatar:"https://s3.bmp.ovh/2026/08/12/HtgLWfKF.png"
            name:"葛城莉莉娅"
            prize:"REVERSI"
        character_5:
            avatar:"https://s3.bmp.ovh/2026/08/12/CssulHTp.png"
            name:"仓本千奈"
            prize:"梦之感应"
        character_6:
            avatar:"https://s3.bmp.ovh/2026/08/12/QwNQnSnd.png"
            name:"紫云清夏"
            prize:"REVERSI"
        character_7:
            avatar:"https://s3.bmp.ovh/2026/08/12/90npuxPI.png"
            name:"﻿篠泽广"
            prize:"梦之感应"
        character_8:
            avatar:"https://s3.bmp.ovh/2026/08/12/gw7YWYdS.png"
            name:"姫崎莉波"
            prize:"Ripple Sign"
        character_9:
            avatar:"https://s3.bmp.ovh/2026/08/12/D9ghyufv.png"
            name:"﻿花海佑芽﻿"
            prize:"Begrazia"
        character_10:
            avatar:"https://s3.bmp.ovh/2026/08/12/Pufg1Ymr.png"
            name:"十王星南"
            prize:"Begrazia"
        character_11:
            avatar:"https://s3.bmp.ovh/2026/08/12/iAhTlM6G.png"
            name:"秦谷美铃"
            prize:"Begrazia"
        character_12:
            avatar:"https://s3.bmp.ovh/2026/08/12/I1en6KXc.png"
            name:"有村麻央"
            prize:"Ripple Sign"
        character_13:
            avatar:"https://s3.bmp.ovh/2026/08/12/jyPHC9Sv.jpg"
            name:"贺阳燐羽"
            prize:"SyngUp!"
        character_14:
            avatar:"https://s3.bmp.ovh/2026/08/12/oP6DwamL.png"
            name:"真城优"
            prize:"初星学园"
        character_15:
            avatar:"https://s3.bmp.ovh/2026/08/12/pruzAGvG.png"
            name:"雨夜燕"
            prize:"初星学园"
        character_16:
            avatar:"https://s3.bmp.ovh/2026/08/12/511SijBG.png"
            name:"根绪亚纱里"
            prize:"初星学园"
        character_17:
            avatar:"https://s3.bmp.ovh/2026/08/12/e0VwjX3N.png"
            name:"樱木真乃"
            prize:"illumination STARS"
        character_18:
            avatar:"https://s3.bmp.ovh/2026/08/12/XN1XGeDx.png"
            name:"风野灯织"
            prize:"illumination STARS"
        character_19:
            avatar:"https://s3.bmp.ovh/2026/08/12/OxnOvthR.png"
            name:"八宫巡"
            prize:"illumination STARS"
        character_20:
            avatar:"https://s3.bmp.ovh/2026/08/12/kAlgp2m1.png"
            name:"月冈恋钟"
            prize:"L'Antica"
        character_21:
            avatar:"https://s3.bmp.ovh/2026/08/12/99aq47kN.png"
            name:"田中摩美美"
            prize:"L'Antica"
        character_22:
            avatar:"https://s3.bmp.ovh/2026/08/12/dUqt2Vii.png"
            name:"白濑咲耶"
            prize:"L'Antica"
        character_23:
            avatar:"https://s3.bmp.ovh/2026/08/12/4Bvx2n8U.png"
            name:"三峰结华"
            prize:"L'Antica"
        character_24:
            avatar:"https://s3.bmp.ovh/2026/08/12/GcMI1fyC.png"
            name:"幽谷雾子"
            prize:"L'Antica"
        character_25:
            avatar:"https://s3.bmp.ovh/2026/08/12/JBtD9ptf.png"
            name:"小宫果穗"
            prize:"放学后CLIMAX GIRLS"
        character_26:
            avatar:"https://s3.bmp.ovh/2026/08/12/ul3BN2Bt.png"
            name:"园田智代子"
            prize:"放学后CLIMAX GIRLS"
        character_27:
            avatar:"https://s3.bmp.ovh/2026/08/12/JhIYnozq.png"
            name:"西城树里"
            prize:"放学后CLIMAX GIRLS"
        character_28:
            avatar:"https://s3.bmp.ovh/2026/08/12/ykoJNyF7.png"
            name:"杜野凛世"
            prize:"放学后CLIMAX GIRLS"
        character_29:
            avatar:"https://s3.bmp.ovh/2026/08/12/3EUyReGQ.png"
            name:"有栖川夏叶"
            prize:"放学后CLIMAX GIRLS"
        character_30:
            avatar:"https://s3.bmp.ovh/2026/08/13/GHsX5eK3.png"
            name:"大崎甘奈"
            prize:"ALSTROEMERIA"
        character_31:
            avatar:"https://s3.bmp.ovh/2026/08/13/FotwTjFz.png"
            name:"大崎甜花"
            prize:"ALSTROEMERIA"
        character_32:
            avatar:"https://s3.bmp.ovh/2026/08/13/Qwr0HV09.png"
            name:"桑山千雪"
            prize:"ALSTROEMERIA"
        character_33:
            avatar:"https://s3.bmp.ovh/2026/08/13/2btFMi3A.png"
            name:"芹泽朝日"
            prize:"Straylight"
        character_34:
            avatar:"https://s3.bmp.ovh/2026/08/13/X3VF1UMn.png"
            name:"黛冬优子"
            prize:"Straylight"
        character_35:
            avatar:"https://s3.bmp.ovh/2026/08/13/M3Itdpn1.png"
            name:"和泉爱依"
            prize:"Straylight"
        character_36:
            avatar:"https://s3.bmp.ovh/2026/08/13/tosGPRcS.png"
            name:"浅仓透"
            prize:"noctchill"
        character_37:
            avatar:"https://s3.bmp.ovh/2026/08/13/3DidSfyc.png"
            name:"樋口圆香"
            prize:"noctchill"
        character_38:
            avatar:"https://s3.bmp.ovh/2026/08/13/oOpk3ftk.png"
            name:"福丸小糸"
            prize:"noctchill"
        character_39:
            avatar:"https://s3.bmp.ovh/2026/08/13/fjcbGfi1.png"
            name:"市川雏菜"
            prize:"noctchill"
        character_40:
            avatar:"https://s3.bmp.ovh/2026/08/13/2qcdLuH6.png"
            name:"七草日花"
            prize:"SHHis"
        character_41:
            avatar:"https://s3.bmp.ovh/2026/08/13/4QmIFE7l.png"
            name:"绯田美琴"
            prize:"SHHis"
        character_42:
            avatar:"https://s3.bmp.ovh/2026/08/13/FYiOx4HR.png"
            name:"斑鸠路加"
            prize:"CoMETIK"
        character_43:
            avatar:"https://s3.bmp.ovh/2026/08/13/HJ2pTRFK.png"
            name:"铃木羽那"
            prize:"CoMETIK"
        character_44:
            avatar:"https://s3.bmp.ovh/2026/08/13/7OucOFB1.png"
            name:"郁田阳希"
            prize:"CoMETIK"
        character_45:
            avatar:"https://s3.bmp.ovh/2026/08/13/OHWAOBke.png"
            name:"七草叶月"
            prize:"283事务所"
