module.exports=
    name:"尼古喵喵"
    opening:"1"
    skin_tip:"你的身份"
    author:"1"
    lastModified:"2026-07-21T07:29:14.680Z"
    vote:""
    sunrise:""
    sunset:""
    icon:""
    background_color:"#000000"
    color:"#ff00a6"
    lockable:true
    isAvailable:->
        return true
    skins:
        character_1:
            avatar:"https://s3.bmp.ovh/2026/07/21/r9v1Hfrx.png"
            name:"尼古喵喵"
            prize:""
        character_2:
            avatar:"https://s3.bmp.ovh/2026/07/21/lPgxFK7p.png"
            name:"酒精喵喵"
            prize:""
        character_3:
            avatar:"https://s3.bmp.ovh/2026/07/21/rBQgqQWe.png"
            name:"妹子喵喵"
            prize:""
        character_4:
            avatar:"https://s3.bmp.ovh/2026/07/21/MMlrFs31.png"
            name:"嗑药喵喵"
            prize:""
        character_5:
            avatar:"https://s3.bmp.ovh/2026/07/21/bIcjlGUT.png"
            name:"性爱喵喵"
            prize:""
        character_6:
            avatar:"https://s3.bmp.ovh/2026/07/21/nAp3ZoMK.png"
            name:"关西喵喵"
            prize:""
        character_7:
            avatar:"https://s3.bmp.ovh/2026/07/21/yXLvkEXk.png"
            name:"房东"
            prize:""
