module.exports=
    name:"狼人杀"
    opening:""
    skin_tip:"你的身份"
    author:""
    lastModified:"2026-09-04T03:55:41.825Z"
    vote:""
    sunrise:""
    sunset:""
    icon:""
    background_color:"#000000"
    color:"#ff00a6"
    lockable:true
    isAvailable:->
        return true
    skins:
        character_1:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrlWqaPOftU4KNjehymBGs9-_Dohp8AALEIAAC34DQVEAW2uv3p8MIPQQ.jpg"
            name:"安娜・克莱尔"
            prize:"预言家"
        character_2:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrl2qaPOut35y1iOYV7xvKj1QYgO2MAALHIAAC34DQVP-Zg-4gcw2PPQQ.jpg"
            name:"梅琳娜·伊芙"
            prize:"女巫"
        character_3:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrsWqaPrOV6JHMaIJjEQpexNWpkOaAAALiIAAC34DQVEg8dSpSBy5bPQQ.jpg"
            name:"帕特里克·亨特"
            prize:"猎人"
        character_4:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrsGqaPrLCtWn0o4--luVHyZ3QnOanAALhIAAC34DQVLT3-I24aqosPQQ.jpg"
            name:"莫林"
            prize:"愚者"
        character_5:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrmGqaPOzLpg4wLDB2eDIEbj9YervJAALIIAAC34DQVLdA8cqCa0ysPQQ.jpg"
            name:"休伯特·威廉"
            prize:"守卫"
        character_6:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrmWqaPO5AGNMmvaq1NTmJ7wABi9gC5wACySAAAt-A0FQ1TwFN6PkhtD0E.jpg"
            name:"艾丽卡·西格莉德"
            prize:"摄梦人"
        character_7:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJro2qaPPsyhHtedhyml-kqtdNuSMNNAALTIAAC34DQVOo9szKkzJPhPQQ.jpg"
            name:"马丁·劳伦斯"
            prize:"魔术师"
        character_8:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrmmqaPO-Nv52yqYcPs5AO5mRgDIvnAALKIAAC34DQVGvay8pP2jVBPQQ.jpg"
            name:"珀西·斯玛特"
            prize:"骑士"
        character_9:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrpGqaPP3_LuQsf1a-R7gcbikrRr1RAALUIAAC34DQVC932N7hcV5VPQQ.jpg"
            name:"莱耶斯"
            prize:"守墓人"
        character_10:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrpWqaPP5kBrpLnCnh4b5my4lZ7eVxAALVIAAC34DQVIeKoubODC1jPQQ.jpg"
            name:"乌鸦"
            prize:"乌鸦"
        character_11:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrm2qaPPHpS2R1Crfeeihl_MFzLeJzAALLIAAC34DQVAxkLx_pOfKXPQQ.jpg"
            name:"潘多"
            prize:"猎魔人"
        character_12:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrpmqaPQABnM-gAtH_av1Q_O2EmwNvbgAC1iAAAt-A0FQ9EnhQk371Jz0E.jpg"
            name:"碧翠丝·卡文迪许"
            prize:"奇迹商人"
        character_13:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrp2qaPQFfJp4fE3vfYNHelgVJsDEHAALXIAAC34DQVKl62Ps86TC8PQQ.jpg"
            name:"加布里埃尔·休斯"
            prize:"定序王子"
        character_14:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrqGqaPQNR5O3YJ1O2ipC4t1jmuwABoAAC2CAAAt-A0FRLSGmqojGzcj0E.jpg"
            name:"德兰·赛伯达"
            prize:"纯白之女"
        character_15:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrnGqaPPJ5GQRUXfotxlrW3MjJMYiAAALMIAAC34DQVI1rJ_50YjssPQQ.jpg"
            name:"尼托克丽丝"
            prize:"炼金魔女"
        character_16:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrqWqaPqfvv692d7G8J7KKX-wPb40IAALaIAAC34DQVO0vD2jODPATPQQ.jpg"
            name:"巴卡洛夫·黑掌"
            prize:"熊"
        character_17:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrqmqaPqkaKaA7asAUxWSanLo2-4XUAALbIAAC34DQVJoQE__gcr4oPQQ.jpg"
            name:"榊"
            prize:"子狐"
        character_18:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrq2qaPqqIjG2w9mTDAAHgXw3mxb8DBwAC3CAAAt-A0FTY-JISZjD-Uj0E.jpg"
            name:"泡泡公爵"
            prize:"河豚"
        character_19:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrrGqaPqyPRt3exFKYJc4g5iAaA9B3AALdIAAC34DQVDh4jAYzo5itPQQ.jpg"
            name:"瑟林"
            prize:"白猫"
        character_20:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrrWqaPq6ebTpo26WU4EHgZTM9qY9GAALeIAAC34DQVISCAfBwjGRvPQQ.jpg"
            name:"羊驼"
            prize:"羊驼"
        character_21:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrrmqaPq-u4Sk86zoS7Xu7NMW4Jw04AALfIAAC34DQVJePQTF50tyPPQQ.jpg"
            name:"特雷西·杰基尔"
            prize:"白昼学者"
        character_22:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrr2qaPrD3dsoJUidOGQwWNe0HWfwQAALgIAAC34DQVD5QDCDHIchTPQQ.jpg"
            name:"米尔恰·日冕"
            prize:"流光伯爵"
        character_23:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrnWqaPPT3QaCGxk-DfUx77QlgIzOXAALNIAAC34DQVOsTDfRzuxLrPQQ.jpg"
            name:"薇薇安"
            prize:"魔镜少女"
        character_24:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrnmqaPPXsP2qpExWox4sx01DRxSFRAALOIAAC34DQVPyVdZtt2nRAPQQ.jpg"
            name:"狼人"
            prize:"人狼"
        character_25:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrsmqaPrQSMSHjkWPlDH7_Eq8ZF1a0AALjIAAC34DQVDEMhbcSgASjPQQ.jpg"
            name:"沃尔夫"
            prize:"狼王"
        character_26:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrs2qaPrbn6Hx8UY-wqxAFOpEyRYOqAALkIAAC34DQVE447x32QGQmPQQ.jpg"
            name:"沃丁"
            prize:"白狼王"
        character_27:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrn2qaPPajp_NBmMPIlGpuj8p8UfjwAALPIAAC34DQVJOFkVvIJh-qPQQ.jpg"
            name:"格拉海德"
            prize:"恶灵骑士"
        character_28:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrtGqaPrcEowG02iMrst-szCIrCIR5AALlIAAC34DQVDSlq3IAAVJxID0E.jpg"
            name:"塔莉莎·莱斯利"
            prize:"狼美人"
        character_29:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrtWqaPriZAwvkbpHxM9yBpD9xRl6jAALmIAAC34DQVM7lE4dsvt_UPQQ.jpg"
            name:"伊兰库斯"
            prize:"石像鬼"
        character_30:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrtmqaProvl0qxtglZgIpC3yiFaQ3qAALnIAAC34DQVC3jwIyH2vAbPQQ.jpg"
            name:"安托鲁斯"
            prize:"隐狼"
        character_31:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrt2qaPrvdXi95tuWEdc8fo5gtp8_wAALoIAAC34DQVFi_I1SrveUMPQQ.jpg"
            name:"安德烈"
            prize:"血月使徒"
        character_32:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJroGqaPPi6hS4nPTraHYQlZoKggaxGAALQIAAC34DQVLXfE_bYRiPVPQQ.jpg"
            name:"彼得·菲茨杰拉德"
            prize:"噩梦之影"
        character_33:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJruGqaP4vALo71XCm58mTr65UOG5sNAAL2IAAC34DQVIUbzxg0rs55PQQ.jpg"
            name:"凡妮莎·达特"
            prize:"蚀时狼妃"
        character_34:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJruWqaP4xtLTY-GVh9sauaj2lFvg5jAAL3IAAC34DQVGuOUIECy6N6PQQ.jpg"
            name:"希兰·沃克"
            prize:"狼巫"
        character_35:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrumqaP44QDodX1CVifMwlPVEW-WWqAAL4IAAC34DQVA1cFBkkYDA-PQQ.jpg"
            name:"厄普顿·基普林"
            prize:"狼鸦之爪"
        character_36:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJru2qaP49y3Xm-cgxyG-4oBQGTiKrvAAL5IAAC34DQVIvC2vqPwNoFPQQ.jpg"
            name:"维纳斯·海德"
            prize:"寂夜导师"
        character_37:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrvGqaP5AlYsX2zuqAvhe8-SeK78LOAAL6IAAC34DQVHQynTF0XF3CPQQ.jpg"
            name:"瓦拉琪·猎日"
            prize:"蚀日侍女"
        character_38:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrvWqaP5E3NPnFkr-w_OdtutwBP6oaAAL7IAAC34DQVIQeiSrJHm-mPQQ.jpg"
            name:"库德拉·月冕"
            prize:"夜之贵族"
        character_39:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrvmqaP5OxzI8luwVhCq0xYOdeBqz8AAL8IAAC34DQVB3r-Pw_bG3oPQQ.jpg"
            name:"爱德华·暮冠"
            prize:"寻香魅影"
        character_40:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrwGqaQB1l3YezVvxDCPjIJRR6n9MrAAIEIQAC34DQVEcQUWwqJ0sfPQQ.jpg"
            name:"丘比特"
            prize:"丘比特"
        character_41:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJroWqaPPn6ov5JakEuqTHCuBaAWwABHQAC0SAAAt-A0FQRMY20FRU6sj0E.jpg"
            name:"红发波尔顿"
            prize:"盗贼"
        character_42:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrv2qaQANAl-S8w8F5hiqwfWXf7YJNAAICIQAC34DQVFBxdRv9_Bm2PQQ.jpg"
            name:"御"
            prize:"咒狐"
        character_43:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJromqaPPoKBBi33ookpYBZhHDs2F4dAALSIAAC34DQVF2x96raCW6QPQQ.jpg"
            name:"蕾妮·英格索尔"
            prize:"暗恋者"
        character_48:
            avatar:"https://piv.cc.cd/file/BQACAgUAAyEGAASLVN5eAAJrlmqaPOklA-4Zphy1HdekL9BoOYW1AALFIAAC34DQVGff6IXTcWvYPQQ.jpg"
            name:"平民"
            prize:"村人"
